In [4]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
print(np.__version__)

1.21.5


In [4]:
pip list

Package                           Version
--------------------------------- --------------------
aiohttp                           3.8.1
aiosignal                         1.2.0
alabaster                         0.7.12
altair                            4.2.0
anaconda-client                   1.9.0
anaconda-navigator                2.2.0
anaconda-project                  0.10.2
analytics-python                  1.4.0
antiword                          0.1.0
anyio                             3.5.0
apeye                             1.2.0
appdirs                           1.4.4
argcomplete                       2.0.0
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.2
astroid                           2.6.6
astropy                           5.0.4
asttokens                         2.0.5
async-timeout                     4.0.1
atomicwrites                      1.4.0
attrs                             21.4.0
Automat           

In [1]:
pip install --upgrade [numpy]==[1.23.3]

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '[numpy]==[1.23.3]'


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr=np.array(42) # o D array
arr


array(42)

1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [8]:
arr=np.array([1,2,32,51,4])#1D
arr

array([ 1,  2, 32, 51,  4])

In [9]:
arr=np.array([[1,2,3],[4,5,6]])#2D
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr=np.array([[[1,23,21],[23,54,5]],[[34,65,78],[76,45,65]]])#3
print(arr)

[[[ 1 23 21]
  [23 54  5]]

 [[34 65 78]
  [76 45 65]]]


In [11]:
arr=np.array([[[1,23,21],[23,54,5],[34,65,78]]])
print(arr)

[[[ 1 23 21]
  [23 54  5]
  [34 65 78]]]


In [12]:
a=np.array(42)
b=np.array([1,2,32,51,4])#1D
c=np.array([[1,2,3],[4,5,6]])#2D
d=np.array([[[1,23,21],[23,54,5]],[[34,65,78],[76,45,65]]])#3

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr=np.array([1,2,3,4],ndmin=5)#ndmin
print(arr)

[[[[[1 2 3 4]]]]]


In [14]:
arr.ndim

5

# NumPy Array Indexing
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [15]:
arr=np.array([0,1,2,3,4,6,9,85,21,65,14])
arr[0]

0

In [16]:
arr[6]

9

In [17]:
print(arr[2]+arr[7])#2+85

87


In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr[1,3]#1st row 3rd column

9

In [20]:
arr[0,4]

5

In [21]:
arr[0,1]

2

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
print(arr[0,1,2])#first array[0],first row[1] and 2nd column[2]

6


In [24]:
print(arr[-1,-1,-1])#negative indexig

12


In [25]:
print(arr[-1,-1,-3])

10


In [26]:
print(arr[-1,-2,-3])

7


### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [5]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]#first include last exclude

array([2, 3, 4, 5])

In [6]:
arr[:4]

array([1, 2, 3, 4])

In [7]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[2:]

array([3, 4, 5, 6, 7])

In [10]:
arr[2:8:2]

array([3, 5, 7])

In [11]:
arr[::2]

array([1, 3, 5, 7])

In [12]:
arr[1::2]

array([2, 4, 6])

In [13]:
arr[1::]

array([2, 3, 4, 5, 6, 7])

In [20]:
arr


array([1, 2, 3, 4, 5, 6, 7])

In [22]:
arr=np.array([1, 2, 3, 4, 5, 6, 7,54,52,56,54,52,854,4])

In [23]:
arr[-3]

52

In [27]:
arr[-7:-1]

array([ 54,  52,  56,  54,  52, 854])

In [28]:
arr[:-1]

array([  1,   2,   3,   4,   5,   6,   7,  54,  52,  56,  54,  52, 854])

In [29]:
arr[-1:]

array([4])

In [33]:
arr[-10:-2:2]

array([ 5,  7, 52, 54])

In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 52,14,16,95], [6, 7, 8, 9, 10,25,17,95]])
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4 52 14 16 95]
 [ 6  7  8  9 10 25 17 95]]
[7 8 9]


In [38]:
arr[0,1:8:2]

array([ 2,  4, 14, 95])

In [39]:
arr[1,1]

7

In [41]:
arr[1:3,1]

array([7])

In [42]:
arr[1,3:-1]

array([ 9, 10, 25, 17])

### NumPy Data Types

In [43]:
arr.dtype

dtype('int32')

In [44]:
arr1 = np.array(['apple', 'banana', 'cherry'])
arr1.dtype

dtype('<U6')

In [47]:
arr=np.array([[ 1,  2,  3,  4, 52, 14, 16, 95],
       [ 6,  7,  8,  9, 10, 25, 17, 95]],dtype="S")

In [48]:
arr

array([[b'1', b'2', b'3', b'4', b'52', b'14', b'16', b'95'],
       [b'6', b'7', b'8', b'9', b'10', b'25', b'17', b'95']], dtype='|S2')

In [50]:
arr.dtype

dtype('S2')

In [52]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [53]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [56]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)#no of array, row,column

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [70]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in arr:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [68]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [71]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
2
3
4
5
6
7


In [72]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
for x in arr:
    for y in x:
        for z in y:
            print(y)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[2 3 4]
[2 3 4]
[2 3 4]
[5 6 7]
[5 6 7]
[5 6 7]


In [73]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
for x in arr:
    for y in x:
        for z in y:
            print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]


In [76]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
for x in arr:
    for y in x:
        print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]


In [77]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0

In [82]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [79]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [80]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)#stack

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [83]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))#hstack

print(arr)

[1 2 3 4 5 6]


In [84]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [85]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [86]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
